jobs:
  - job: macOS
    strategy:
      matrix:
        py37:
          python.version: "3.7"
    pool:
      vmImage: macOS-10.14
    steps:
      # https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/anaconda?view=azure-devops&tabs=macos
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH

      # On Hosted macOS, the agent user doesn't have ownership of Miniconda's installation directory/
      # We need to take ownership if we want to update conda or install packages globally
      - bash: sudo chown -R $USER $CONDA
        displayName: Take ownership of conda installation
      - template: templates/setup-script-nix.yml
      - template: templates/nb-docs-nix.yml

  - job: linux
    strategy:
      matrix:
        py37:
          python.version: "3.7"
    pool:
      vmImage: ubuntu-16.04
    steps:
      # https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/anaconda?view=azure-devops&tabs=ubuntu-16-04
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH

      - template: templates/setup-script-nix.yml
      - template: templates/nb-docs-nix.yml

#   - job: windows
#     strategy:
#       matrix:
#         py37:
#           python.version: "3.7"
#         py36:
#           python.version: "3.6"
#     pool:
#       vmImage: vs2017-win2016
#     steps:
#       # https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/anaconda?view=azure-devops&tabs=vs2017
#       - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
#         displayName: Add conda to PATH

#       - template: templates/setup-script-win.yml
#       - template: templates/nb-docs-win.yml
